 var name = prompt("What's your name?")
 console.log("Your name's " + name)
 var example = +prompt("4+5 = ?")
 console.log("Your answer for 1st example is: " +example)
 var examle = +prompt("19-8 = ?")
 console.log("Your answer for 1st example is: " +examle)
 var exale = +prompt("45*2 = ?")
 console.log("Your answer for 1st example is: " +exale)
 var exle = +prompt("21/3 = ?")
 console.log("Your answer for 4th example is: " +exle)
 var xale = +prompt("14%5 = ?")
 console.log("Your answer for 5th example is: " +xale)